# Encoding: UTF-8
project_name: az

before:
  hooks:
    # - go mod tidy
    # - go generate ./...
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -mod=vendor
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/bdwyertech/go-az/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/bdwyertech/go-az/cmd.ReleaseVer={{.Version}}
      - -X github.com/bdwyertech/go-az/cmd.ReleaseDate={{.Date}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ONLY_BINARY*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  # disable: true

signs:
  # - artifacts: checksum
  # - artifacts: all
